version: '3.8'

services:
  scraper:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./scraped_data:/app/scraped_data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 